In [1]:
from model_structures.biggan_classifier import BigGANClassifier

classifier = BigGANClassifier(resolution=32, output_dim=2)

Param count for Ds initialized parameters: 651136


In [1]:
from model_structures.resnet import ResNet
net = ResNet(num_classes=1000)

In [3]:
def extract_layer_outputs(model, x):
    layer_outputs = []

    # conv1
    x = model.resnet.conv1(x)
    x = model.resnet.bn1(x)
    x = model.resnet.relu(x)
    x = model.resnet.maxpool(x)
    layer_outputs.append(x)
    
    # layer1
    x = model.resnet.layer1(x)
    layer_outputs.append(x)

    # layer2
    x = model.resnet.layer2(x)
    layer_outputs.append(x)

    # layer3
    x = model.resnet.layer3(x)
    layer_outputs.append(x)

    # layer4
    x = model.resnet.layer4(x)
    layer_outputs.append(x)

    return layer_outputs

In [15]:
import torch
x = torch.rand((1,4,32,32))
layer_outputs = extract_layer_outputs(net, x)

In [ ]:
np.cumprod(output.shape[-1])

In [20]:
import numpy as np
for output in layer_outputs:
    print(output.shape, np.cumprod(output.shape)[-1])

torch.Size([1, 64, 16, 16]) 16384
torch.Size([1, 128, 8, 8]) 8192
torch.Size([1, 256, 4, 4]) 4096
torch.Size([1, 512, 2, 2]) 2048


In [7]:
import torch.nn as nn
net.resnet.avgpool = nn.Identity()
net.resnet.fc = nn.Identity()

In [8]:
o = net(x)

In [11]:
layer_outputs[-1].reshape(-1)

tensor([2.8098, 0.4193, 0.7604,  ..., 0.0000, 3.1111, 0.0000],
       grad_fn=<ReshapeAliasBackward0>)

In [9]:
o

tensor([[2.8098, 0.4193, 0.7604,  ..., 0.0000, 3.1111, 0.0000]],
       grad_fn=<ReshapeAliasBackward0>)

In [13]:
(layer_outputs[-1].reshape(-1)==o).sum()

tensor(2048)

In [2]:
net

ResNet(
  (resnet): ResNet(
    (conv1): Conv2d(4, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU(inplace=True)
    (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    (layer1): Sequential(
      (0): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace=True)
        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (1): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_runni

In [15]:
import torch
x = torch.rand(4,4,32,32)

In [3]:
import torch.nn as nn
features = nn.Sequential(*list(net.resnet.children())[:-2])

In [5]:
# 修改模型结构
net.resnet.avgpool = nn.Identity()
net.resnet.fc = nn.Identity()

In [19]:
if "":
    print('1')
else:
    print('0')

0


In [16]:
out1 = net(x)
out1

tensor([[1.6681, 2.1741, 1.1559,  ..., 2.1739, 2.4794, 1.6783],
        [0.0000, 0.0000, 0.0000,  ..., 0.9067, 2.7994, 2.2949],
        [2.6841, 2.1029, 2.1787,  ..., 0.0000, 0.5557, 0.0000],
        [0.0000, 0.0000, 0.6730,  ..., 0.0000, 0.0000, 0.0000]],
       grad_fn=<ReshapeAliasBackward0>)

In [18]:
out1.mean(dim=0).shape

torch.Size([2048])

In [9]:
out1.shape

torch.Size([1, 2048])

In [10]:
out2.shape

torch.Size([1, 512, 2, 2])

In [14]:
sum(sum(out2.resize(1,2048)==out1))

/home/AD/xiw136/anaconda3/envs/DiT/lib/python3.11/site-packages/torch/_tensor.py:775: UserWarning: non-inplace resize is deprecated
  warnings.warn("non-inplace resize is deprecated")


tensor(2048)

In [8]:
out2 = features(x)
out2

tensor([[[[2.7232, 0.0000],
          [0.9985, 0.0000]],

         [[2.0500, 0.0000],
          [1.8434, 0.0000]],

         [[1.0545, 0.0000],
          [2.3171, 0.3804]],

         ...,

         [[2.0955, 0.0000],
          [0.0000, 1.0839]],

         [[0.0000, 0.0000],
          [2.8360, 1.1948]],

         [[0.1346, 1.2154],
          [0.0000, 2.0964]]]], grad_fn=<ReluBackward0>)

In [4]:
features

Sequential(
  (0): Conv2d(4, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
  (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (2): ReLU(inplace=True)
  (3): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (4): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Con

In [2]:
net

ResNet(
  (resnet): ResNet(
    (conv1): Conv2d(4, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU(inplace=True)
    (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    (layer1): Sequential(
      (0): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace=True)
        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (1): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_runni